@startuml Level Logic CD

package "Level Logic" {

    class LevelManager<MonoBehaviour>
    {
    + static LevelManager Instance
    - static LevelManager _instance
    - LevelData levelData
    - GameObject humanSpawnPos
    - GameObject catSpawnPos
    - Stopwatch _stopWatch
    - GameObject _human
    - GameObject _cat
    - PerspectiveManager _perspectiveManager
    - NetworkManager _networkManager
  
    + void RestartLevel()
    + void CompleteLevel()
    + void ExitLevel()
    - CharacterRole DetermineLocalRole()
    - void FetchPlayers()
    - void PositionPlayers()
    }
}
@enduml