@startuml architecture
' dont show class members for simplicity
hide member
!pragma layout smetana

package "Parallax CD" {

    !include Asymmetrical Perspective POC/AsymmetricalPerspectiveCD.puml

''''''''''''''''''''''''''''''''''''''''''''''''''''''''

    package "Application Data Management" {
        interface ISaveSystem
        class PlayerPrefs implements ISaveSystem
        class SettingsData
        class ScoreData 
    }
    PlayerPrefs --> SettingsData 
    PlayerPrefs --> ScoreData 
    
''''''''''''''''''''''''''''''''''''''''''''''''''''''''

    package "Game State Management" {
        class MainMenu<active upon game launch>
        class Guide
        class MultiplayerLobby
        class SettingsMenu
        class LevelSelector<transitions to level scenes>
    }
    MainMenu ---> MultiplayerLobby 
    MainMenu --> SettingsMenu 
    MainMenu --> Guide 
    MultiplayerLobby --> LevelSelector 

''''''''''''''''''''''''''''''''''''''''''''''''''''''''

    package "Multiplayer Orchestration" {
        interface INetworkManager
        class NetworkManager implements INetworkManager
    }

''''''''''''''''''''''''''''''''''''''''''''''''''''''''

    package "Game Logic" {
        class LevelObjectiveManager
        class LevelTimer
        class LevelStartManager
        class LevelEndManager
        class Hazard
    }
    LevelEndManager -down-> LevelTimer 
    LevelEndManager -down-> LevelObjectiveManager 

''''''''''''''''''''''''''''''''''''''''''''''''''''''''

    package "Character" {
        interface IPlayerInterface
        class PlayerInterface 

        class PlayerStats

        class CameraController
        class MovementController
        class JumpController
        class DragController
        class PickupController
    }
    PlayerInterface .|> IPlayerInterface
    IPlayerInterface -up-> PlayerStats 
    IPlayerInterface <-- MovementController
    IPlayerInterface <-- JumpController
    IPlayerInterface <-- DragController
    IPlayerInterface <-- PickupController

''''''''''''''''''''''''''''''''''''''''''''''''''''''''

' connections
INetworkManager <- MultiplayerLobby : Handle multiplayer sessions

SettingsMenu -> ISaveSystem : Save settings changes
ISaveSystem <--- LevelSelector : Load scores
ISaveSystem <---- LevelEndManager : Save level completion data

LevelStartManager -up-> LevelTimer : Start level timer
LevelStartManager ---> IPlayerInterface : Unfreeze player controls
LevelStartManager --> IPerspectiveManager : Initial perspective setup 

Hazard --> IPlayerInterface : Apply hazard effects

LevelTimer -[hidden]- LevelStartManager
LevelTimer -[hidden]- Hazard

}
@enduml