@startuml FullCD

hide members

package "Parallax CD" 
{
    !include LevelLogic/LevelLogicCD.puml
    !include Asymmetrical Perspective/AsymmetricalPerspectiveCD.puml
    !include Multiplayer/MultiplayerCD.puml
    !include GUI/guiCD.puml

    class NetworkManager #line.dashed:black

    LevelManager --> PerspectiveManager
    LevelManager --> NetworkManager
    MultiplayerPage --> MultiplayerManager
}

@enduml