@startuml FullCD

package "Parallax CD" 
{
    !include Level Logic/LevelLogicCD.puml
    !include Asymmetrical Perspective/AsymmetricalPerspectiveCD.puml
    !include Network/NetworkCD.puml

    LevelManager --> IPerspectiveManager
    INetworkManager <--- PerspectiveManager
}

@enduml