@startuml
title MainMenu UI

[*] --> MainMenu

state MainMenu {
    MainMenu : Entry point of the game
}

state LobbyCreationMenu {
    LobbyCreationMenu : Select Lobby Option
}

state CreatePrivateLobby {
    CreatePrivateLobby : Host Private Lobby
}

state CreatePublicLobby {
    CreatePublicLobby : Host Public Lobby
}

state JoinPrivateLobby {
    JoinPrivateLobby : Join with Lobby Code
}

state JoinPublicLobby {
    JoinPublicLobby : Join Public Matchmaking
}

state GameStart {
    GameStart : Change Screen to Lobby Menu
}

state Guide {
    [*] --> GuidePage1

    GuidePage1 --> GuidePage2 : Next
    GuidePage2 --> GuidePage3 : Next
    GuidePage3 --> GuidePage4 : Next
    GuidePage4 --> GuidePage1 : Next

    GuidePage1 --> GuidePage4 : Previous
    GuidePage2 --> GuidePage1 : Previous
    GuidePage3 --> GuidePage2 : Previous
    GuidePage4 --> GuidePage3 : Previous
}

state SettingsMenu {
    SettingsMenu : Audio / Controls
}

state QuitGame {
    QuitGame : Exit Application
}

MainMenu --> LobbyCreationMenu : Play Button

LobbyCreationMenu --> CreatePrivateLobby : Host Private Game
LobbyCreationMenu --> CreatePublicLobby : Host Public Game
LobbyCreationMenu --> JoinPrivateLobby : Join Private Game
LobbyCreationMenu --> JoinPublicLobby : Join Public Game

CreatePrivateLobby --> GameStart : Create Lobby
CreatePublicLobby --> GameStart : Create Lobby
JoinPrivateLobby --> GameStart : Join with Code
JoinPublicLobby --> GameStart : Join Lobby

LobbyCreationMenu --> MainMenu : Close

MainMenu --> Guide : Open Guide
MainMenu --> SettingsMenu : Open Settings
MainMenu --> QuitGame : Quit Button

Guide --> MainMenu : Close
SettingsMenu --> MainMenu : Close

QuitGame --> [*]

@enduml