@startuml asymmetrical perspective CD


package "Asymmetrical Perspective" {

    ' Enum usedd to deine the target perspective
    enum PerspectiveProfile
    {
        Human
        Cat
    }

    interface IPerspectiveManager
    {
        + void ApplyPerspectiveProfile()
    }

    class PerspectiveManager<MonoBehaviour>
    {
        - BaseAsymProperty[] _asymProperties
        - INetworkManager _networkManager
    }

    !include AsymmetricalPropertyCD.puml

    IPerspectiveManager <|.. PerspectiveManager
    PerspectiveManager -> PerspectiveProfile
    PerspectiveManager --> base
    PerspectiveProfile <-- base
}
@enduml