@startuml asymmetrical perspective CD

package "Asymmetrical Perspective" {

    class PerspectiveManager<MonoBehaviour>
    {
        - BaseAsymProperty[] _asymProperties
        + void ApplyPerspective(CharacterRole role)
    }

    !include AsymmetricalPropertyCD.puml

    PerspectiveManager --> base
}
@enduml