@startuml asymmetrical perspective CD


package "Asymmetrical Perspective" {

    ' Enum usedd to deine the target perspective
    enum PerspectiveProfile
    {
        Human
        Cat
    }

    interface IPerspectiveManager
    {
        + void ApplyPerspectiveProfile(PerspectiveProfile profile)
    }

    class PerspectiveManager<MonoBehaviour>
    {
        - BaseAsymProperty[] _asymProperties
    }

    !include AsymmetricalPropertyCD.puml

    PerspectiveProfile <-up- IPerspectiveManager 
    IPerspectiveManager <|.. PerspectiveManager
    PerspectiveManager --> base
    PerspectiveProfile <-- base
}
@enduml